//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 07.07.2020 09:53:38
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;

namespace ChinokDalGenerated
{

    /// <summary>
    /// There are no comments for ChinokDalGenerated.Artist, ChinokDalGenerated in the schema.
    /// </summary>
    public partial class Artist {

        #region Extensibility Method Definitions

        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();

        #endregion
        /// <summary>
        /// There are no comments for Artist constructor in the schema.
        /// </summary>
        public Artist()
        {
            this.Albums = new HashSet<Album>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for ArtistId in the schema.
        /// </summary>
        public virtual int ArtistId
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Name in the schema.
        /// </summary>
        public virtual string Name
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Albums in the schema.
        /// </summary>
        public virtual ISet<Album> Albums
        {
            get;
            set;
        }
    }

}
